### ISSUE TITLE
MPR version of makedeb-makepkg issues (beta and stable)

### ISSUE THREAD

**Issue by not-a-dev-stein** [hwittenborn/makedeb#28]
### Issue

There are 2 main issues with the MPR version of makedeb-makepkg, on stable, when trying to install a package it gives the following error:

`/usr/bin/makedeb: line 716: /usr/share/makepkg/util/message.sh: No such file or directory`

And with the beta version it fails to create the `makepkg.conf` file, giving an error calling it out when trying to install or update packages.

### Installation source

makedeb Package Repository (MPR)

### Installed release type

Beta

### Installed makedeb version

6.3.1-1

### Installed makepkg version

8.4.0-1

**Comment by hwittenborn** [comment]
This should be fixed in the alpha release now, but I'll try to (hopefully) deploy everything to beta shortly.

**Comment by hwittenborn** [comment]
Everything should be deployed to stable now. Feel free to reopen if the issue still persists.

**Comment by not-a-dev-stein** [comment]
With the stable version I still get the same error:
`/usr/bin/makedeb: line 716: /usr/share/makepkg/util/message.sh: No such file or directory`

Will test beta soon enough to check if that version works.

EDIT: oh nvm, reinstalling the repo version before changing to the MPR version solved it
